### ISSUE TITLE
gxc wallet 运行不起来

### ISSUE THREAD

**Issue by gtrandxiangyu** [gxchain/gxs-wallet#27]
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$ npm install
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$ npm start

> gxb-mobile-wallet@1.0.0 start /home/yangxing/work/gxc_wallet/gxs-wallet
> node build/dev-server.js

isProd false
> Starting dev server...
Error: Module build failed: Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:32:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/through2/node_modules/readable-stream/readable.js:12:30)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at eval (webpack-internal:///0:1:7)
    at Object.eval (eval at <anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:657:1)
    at __webpack_require__ (eval at <anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:601:30)
    at eval (eval at <anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:650:37)
    at eval (eval at <anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22), <anonymous>:653:10)
    at Compilation.<anonymous> (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/lib/compiler.js:48:22)
    at Compilation.applyPluginsAsyncSeries (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compilation.js:635:10)
    at Compilation.applyPluginsAsyncSeries (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compilation.js:631:9)
    at Compilation.applyPluginsAsyncSeries (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compilation.js:579:8)
    at /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compiler.js:493:16
    at /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/webpack/lib/Compilation.js:452:13)

**Comment by lanhaoxiang** [comment]
```
rm -rf node_modules
npm install
```
